# Generated by Django 3.2.9 on 2022-06-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('price_usd', models.FloatField()),
                ('price_rub', models.FloatField()),
                ('delivery_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TableBuffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('price_usd', models.FloatField()),
                ('price_rub', models.FloatField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
